"""Create a linked fresh Suite using selected immutable Cases from an earlier Suite."""

from copy import deepcopy
from dataclasses import dataclass, replace
from pathlib import Path

from agentbench.harness import SuiteRunner
from agentbench.harness.result import BenchmarkSuiteResult
from agentbench.harness.session import SuiteProvenanceError, SuiteStore
from agentbench.harness.session.store import read_suite
from agentbench.harness.session.snapshot import suite_snapshot
from agentbench.harness.session.codec import prepared_from_json
from agentbench.harness.session.cases import verify_prepared
from agentbench.harness.session.plan import registrations_from_plan
from agentbench.harness.session.references import history_guard, register_suite_reference
from agentbench.cli.history import PROJECT_ROOT

from .configuration import build_saved_runner, runner_configuration


@dataclass(frozen=True)
class ReuseExecution:
    """Shared reuse Suite location and its independently scored Case results."""

    directory: Path
    result: BenchmarkSuiteResult


def prepare_reuse(directory, *, environ, root=None, model=None, max_steps=None,
                  runner=None, suite_id=None, selection=None):
    """Retain saved Cases in a new Suite without executing any Agent.

    Args:
        directory: Original canonical Suite directory, including an active Suite.
        environ: Current credentials/runtime defaults, excluded from saved plans.
        root: New Suite parent directory; defaults to the original Suite's parent.
        model: Optional Agent model override forwarded to the ordinary runner builder.
        max_steps: Optional positive SDK max_steps option for the new execution.
        runner: Optional already configured runner for offline/injected integrations.
            Explicit overrides require its reported configuration to match them.
        suite_id: Optional new identity; normally generated by SuiteRunner.
        selection: Optional (Agent ID, zero-based Case index) positions. Selected
            slots are renumbered densely; their original positions remain in origin.
    Returns:
        (new_directory, configured_runner). No old result, Attempt or SDK Run is copied.
    Raises:
        SuiteProvenanceError for any missing, changed or non-persisted Case. Source
        provenance differences are allowed and captured freshly in the new plan.
    """
    inputs = reuse_inputs(directory, environ=environ, model=model, max_steps=max_steps,
                          runner=runner, selection=selection)
    return create_reuse(inputs, environ=environ, root=root, suite_id=suite_id)


@dataclass(frozen=True)
class ReuseInputs:
    source: Path
    plan: dict
    snapshot: dict
    registrations: tuple
    originals: tuple
    configuration: dict
    runner: object


def reuse_inputs(directory, *, environ, model=None, max_steps=None, runner=None, selection=None):
    """Validate and freeze the requested inputs before choosing a destination."""
    if model is not None and (not isinstance(model, str) or not model.strip()):
        raise ValueError('Model override must be a non-empty string')
    if max_steps is not None and (type(max_steps) is not int or max_steps < 1):
        raise ValueError('max_steps must be a positive integer')
    # Plans and retained Cases are immutable. Events are published atomically;
    # one read captures a complete prefix without taking the active writer's lock.
    # retain_case validates the copied bytes again against this snapshot's digest.
    source = Path(directory).resolve()
    plan, events = read_suite(source)
    snapshot = suite_snapshot(plan, events)
    saved_cases = {(job['agent_id'], case['case_index']): case['prepared_case']
                   for job in snapshot['jobs'] for case in job['cases']}
    registrations = registrations_from_plan(plan)
    available = {(agent.agent_id, index) for agent in registrations for index in range(agent.case_count)}
    selection = available if selection is None else set(selection)
    if not selection or not selection <= available:
        raise ValueError('Reuse selection must contain saved Case positions from this Suite')
    selected = []
    originals = []
    for agent in registrations:
        indices = [index for index in range(agent.case_count) if (agent.agent_id, index) in selection]
        if indices:
            selected.append(replace(agent, case_count=len(indices)))
        for new_index, index in enumerate(indices):
            value = saved_cases[(agent.agent_id, index)]
            case = None if value is None else verify_prepared(prepared_from_json(value))
            if case is None or case.artifact_path is None:
                raise SuiteProvenanceError('Reuse requires an intact persisted artifact for every original Case')
            originals.append((agent.agent_id, new_index, case))
    configuration = deepcopy(plan['configuration'])
    if model is not None:
        configuration['model'] = model
    if max_steps is not None:
        configuration['sdk_options'] = {**configuration.get('sdk_options', {}), 'max_steps': max_steps}
    injected = runner is not None
    runner = runner or build_saved_runner(configuration, environ)
    current = runner_configuration(runner)
    if injected and (model is not None or max_steps is not None):
        if current is None:
            raise ValueError('An injected runner must report its applied configuration to accept overrides')
        if (model is not None and current.get('model') != model
                or max_steps is not None and (current.get('sdk_options') or {}).get('max_steps') != max_steps):
            raise ValueError('Injected runner configuration does not match the requested overrides')
    # The builder uses saved semantic options but current code/dependencies.
    configuration = current if current is not None else configuration
    return ReuseInputs(source, plan, snapshot, tuple(selected), tuple(originals), configuration, runner)


def create_reuse(inputs, *, environ, root=None, suite_id=None):
    """Create the first immutable selection of a reuse batch."""
    source, plan, snapshot = inputs.source, inputs.plan, inputs.snapshot
    selected, originals = inputs.registrations, inputs.originals
    configuration, runner = inputs.configuration, inputs.runner
    identifier = suite_id or SuiteRunner.new_suite_id()
    if identifier == plan['suite_id']:
        raise ValueError('Case reuse requires a new Suite identity')
    destination = Path(root).resolve() if root is not None else source.parent
    with history_guard(PROJECT_ROOT):
        register_suite_reference(source, project_root=PROJECT_ROOT)
        with SuiteStore.begin(destination, identifier, selected, configuration=configuration,
                              environ=environ, origin_suite_id=plan['suite_id']) as target:
            register_suite_reference(target.directory, project_root=PROJECT_ROOT)
            target.append({'event': 'suite_cases_reused', 'origin_suite_id': plan['suite_id'],
                           'origin_revision': snapshot['revision'], 'case_count': len(originals)})
            for agent_id, new_index, case in originals:
                target.retain_case(agent_id, replace(case, case_index=new_index), allow_repeated=True)
                target.append({'event': 'case_reused', 'agent_id': agent_id, 'case_index': new_index,
                    'origin': {'suite_id': plan['suite_id'], 'revision': snapshot['revision'], 'agent_id': agent_id,
                               'case_index': case.case_index, 'case_id': case.case_id,
                               'artifact_sha256': case.artifact_sha256, 'content_sha256': case.content_sha256}})
            target.append({'event': 'suite_cases_reuse_completed', 'case_count': len(originals)})
            return target.directory, runner

def execute_reuse(directory, *, environ, root=None, model=None, max_steps=None, runner=None,
                  suite_id=None, on_created=None, on_event=None, run_control=None, selection=None,
                  on_runner=None, command_id=None):
    """Add a fresh execution to a compatible live reuse Suite, or create a new batch."""
    from .reuse_pool import execute_pooled_reuse
    return execute_pooled_reuse(directory, environ=environ, root=root, model=model,
        max_steps=max_steps, runner=runner, suite_id=suite_id, on_created=on_created,
        on_event=on_event, run_control=run_control, selection=selection,
        on_runner=on_runner, command_id=command_id)
