"""Create a linked fresh Suite using every immutable Case from an earlier Suite."""

from copy import deepcopy
from dataclasses import dataclass
from pathlib import Path

from agentbench.harness import SuiteRunner
from agentbench.harness.result import BenchmarkSuiteResult
from agentbench.harness.session import SuiteProvenanceError, SuiteStore
from agentbench.harness.session.references import history_guard, register_suite_reference
from agentbench.cli.history import PROJECT_ROOT

from .configuration import build_saved_runner, runner_configuration
from .recovery import execute_recovery


@dataclass(frozen=True)
class ReuseExecution:
    """New Suite location and its independently scored execution result."""

    directory: Path
    result: BenchmarkSuiteResult


def prepare_reuse(directory, *, environ, root=None, model=None, max_steps=None,
                  runner=None, suite_id=None):
    """Retain all original Cases in a new Suite without executing any Agent.

    Args:
        directory: Original canonical Suite directory; its writer must be inactive.
        environ: Current credentials/runtime defaults, excluded from saved plans.
        root: New Suite parent directory; defaults to the original Suite's parent.
        model: Optional Agent model override forwarded to the ordinary runner builder.
        max_steps: Optional positive SDK max_steps option for the new execution.
        runner: Optional already configured runner for offline/injected integrations.
            Explicit overrides require its reported configuration to match them.
        suite_id: Optional new identity; normally generated by SuiteRunner.
    Returns:
        (new_directory, configured_runner). No old result, Attempt or SDK Run is copied.
    Raises:
        SuiteProvenanceError for any missing, changed or non-persisted Case. Source
        provenance differences are allowed and captured freshly in the new plan.
    """
    if model is not None and (not isinstance(model, str) or not model.strip()):
        raise ValueError('Model override must be a non-empty string')
    if max_steps is not None and (type(max_steps) is not int or max_steps < 1):
        raise ValueError('max_steps must be a positive integer')
    with SuiteStore.open(directory, environ=environ) as source:
        selected = source.registrations
        originals = []
        for agent in selected:
            for index in range(agent.case_count):
                case = source.prepared_case(agent.agent_id, index)
                if case is None or case.artifact_path is None:
                    raise SuiteProvenanceError('Reuse requires an intact persisted artifact for every original Case')
                originals.append((agent.agent_id, case))
        configuration = deepcopy(source.plan['configuration'])
        if model is not None:
            configuration['model'] = model
        if max_steps is not None:
            configuration['sdk_options'] = {**configuration.get('sdk_options', {}), 'max_steps': max_steps}
        injected = runner is not None
        runner = runner or build_saved_runner(configuration, environ)
        current = runner_configuration(runner)
        if injected and (model is not None or max_steps is not None):
            if current is None:
                raise ValueError('An injected runner must report its applied configuration to accept overrides')
            if (model is not None and current.get('model') != model
                    or max_steps is not None and (current.get('sdk_options') or {}).get('max_steps') != max_steps):
                raise ValueError('Injected runner configuration does not match the requested overrides')
        # The builder uses saved semantic options but current code/dependencies.
        configuration = current if current is not None else configuration
        identifier = suite_id or SuiteRunner.new_suite_id()
        if identifier == source.suite_id:
            raise ValueError('Case reuse requires a new Suite identity')
        destination = Path(root).resolve() if root is not None else source.directory.parent
        with history_guard(PROJECT_ROOT):
            register_suite_reference(source.directory, project_root=PROJECT_ROOT)
            with SuiteStore.begin(destination, identifier, selected, configuration=configuration,
                                  environ=environ, origin_suite_id=source.suite_id) as target:
                register_suite_reference(target.directory, project_root=PROJECT_ROOT)
                target.append({'event': 'suite_cases_reused', 'origin_suite_id': source.suite_id,
                               'case_count': len(originals)})
                for agent_id, case in originals:
                    target.retain_case(agent_id, case)
                    target.append({'event': 'case_reused', 'agent_id': agent_id, 'case_index': case.case_index,
                        'origin': {'suite_id': source.suite_id, 'agent_id': agent_id,
                                   'case_index': case.case_index, 'case_id': case.case_id,
                                   'artifact_sha256': case.artifact_sha256, 'content_sha256': case.content_sha256}})
                target.append({'event': 'suite_cases_reuse_completed', 'case_count': len(originals)})
                return target.directory, runner


def execute_reuse(directory, *, environ, root=None, model=None, max_steps=None, runner=None,
                  suite_id=None, on_created=None, on_event=None, run_control=None):
    """Create then execute a linked new Suite; completion never modifies the source Suite.

    ``on_created(Path)`` exposes the durable destination before execution can fail.
    Other inputs have the same meaning as prepare_reuse. The returned ReuseExecution
    contains the new directory and benchmark result, including failed evaluations.
    """
    if run_control is not None:
        run_control.check()
    destination, runner = prepare_reuse(directory, environ=environ, root=root, model=model,
        max_steps=max_steps, runner=runner, suite_id=suite_id)
    if on_created:
        on_created(destination)
    result = execute_recovery(destination, environ=environ, runner=runner,
                              on_event=on_event, run_control=run_control)
    return ReuseExecution(destination, result)
