"""Deterministic TOML encoding of the manifest's JSON-compatible value subset."""

import json
import math
import re

from ..common.errors import BuildError


def _key(value):
    if not isinstance(value, str):
        raise BuildError("TOML keys must be strings")
    return value if re.fullmatch(r"[A-Za-z0-9_-]+", value) else json.dumps(value, ensure_ascii=False)


def _value(value):
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if type(value) is bool:
        return str(value).lower()
    if type(value) in (int, float):
        if isinstance(value, float) and not math.isfinite(value):
            raise BuildError("TOML numbers must be finite")
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(_value(item) for item in value) + "]"
    if isinstance(value, dict):
        return "{ " + ", ".join(f"{_key(key)} = {_value(item)}" for key, item in value.items()) + " }"
    raise BuildError(f"Cannot encode {type(value).__name__} as TOML; null values must be omitted")


def encode_manifest(manifest):
    """Serialize explicit tables/arrays; quoted values cannot inject new sections."""
    lines = ["# Generated by BBA from validated configuration facts."]

    def table(values, path=(), header=None):
        if header:
            lines.extend(["", header])
        for key, value in values.items():
            if not isinstance(value, dict) and not (isinstance(value, list) and value and
                                                    all(isinstance(item, dict) for item in value)):
                lines.append(f"{_key(key)} = {_value(value)}")
        for key, value in values.items():
            nested = (*path, key)
            label = ".".join(_key(part) for part in nested)
            if isinstance(value, dict):
                table(value, nested, f"[{label}]")
            elif isinstance(value, list) and value and all(isinstance(item, dict) for item in value):
                for item in value:
                    table(item, nested, f"[[{label}]]")

    table(manifest)
    return "\n".join(lines) + "\n"
